name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      Run:
        description: "Run mode (true for headless, false for normal)"
        required: false
        default: "true"
      Browser:
        description: "Browser to use for testing"
        required: false
        default: "chrome"
      Env:
        description: "Environment for testing"
        required: false
        default: "sandbox"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Browser
        run: |
          if [ "${{ github.event.inputs.Browser }}" == "chrome" ]; then
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
          elif [ "${{ github.event.inputs.Browser }}" == "firefox" ]; then
            sudo apt-get update
            sudo apt-get install -y firefox
          elif [ "${{ github.event.inputs.Browser }}" == "edge" ]; then
            sudo apt-get update
            wget https://packages.microsoft.com/keys/microsoft.asc -O microsoft.asc
            sudo apt-key add microsoft.asc
            sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge/ stable main"
            sudo apt-get update
            sudo apt-get install -y microsoft-edge-stable
          else
            echo "Unsupported browser: ${{ github.event.inputs.Browser }}"
            exit 1
          fi

      - name: Run tests
        env:
          Run: ${{ github.event.inputs.Run || 'false' }}
          Browser: ${{ github.event.inputs.Browser || 'chrome' }}
          Env: ${{ github.event.inputs.Env || 'sandbox' }}
        run: |
          pytest